### ISSUE TITLE
Emoticons appear in normal text

### ISSUE THREAD

**Issue by mase76** [Hernou/pidgin-EAP#6]
Hi!
I am using the hangouts emoticons in pidgin to be compatible
with android. However the emoticons often appear in the normal
text or timestamps, for example in "(14:32:59)".

**Comment by Hernou** [comment]
I don't understand your problem, you using hangout theme and it don't work for some caracters ? or do you want just use this theme :  https://github.com/stv0g/unicode-emoji/tree/master/android , https://github.com/stv0g/unicode-emoji/blob/master/android/1f601.png in pidgin EAP ?

**Comment by mase76** [comment]
I mean, in some character strings I see smileys, where they should not be. The system often converts some special strings into smileys. The theme I am using is the pidgin default. I only use the hangouts smileys. 

Am 10. März 2015 12:58:03 MEZ, schrieb Hernou <notifications@github.com>:
>I don't understand your problem, you using hangout theme and it don't
>work for some caracters ? or do you want just use this theme : 
>https://github.com/stv0g/unicode-emoji/tree/master/android ,
>https://github.com/stv0g/unicode-emoji/blob/master/android/1f601.png in
>pidgin EAP ?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Hernou/pidgin-EAP/issues/6#issuecomment-78039931

-- 
gpg: 383107c4
https://www.setho.org/people

**Comment by Hernou** [comment]
with what protocol do you have this ? Gtalk, Mygthytext ? If it's hangout for all protocols, maybe can you correct the theme yourself directly on this git ? because I don't use this theme currently...

**Comment by giordano** [comment]
> However the emoticons often appear in the normal
> text or timestamps, for example in "(14:32:59)".

Does this happen in the chat windows or in the log?  It happens in the log also to me, but I don't think it's a bug with this theme, it should be a bug in Pidgin itself

**Comment by mase76** [comment]
I use XMPP (jabber) 

Am 10. März 2015 17:00:54 MEZ, schrieb Hernou <notifications@github.com>:
>with what protocol do you have this ? Gtalk, Mygthytext ? If it's
>hangout for all protocols, maybe can you correct the theme yourself
>directly on this git ? because I don't use this theme currently... 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Hernou/pidgin-EAP/issues/6#issuecomment-78084974

-- 
gpg: 383107c4
https://www.setho.org/people

**Comment by mase76** [comment]
See this picture of a timestamp:
![Uploading pidgin.png . . .]()

**Comment by schmatzler** [comment]
I think this is a Pidgin bug - it happens with ICQ here, too - but only in the chat history.

**Comment by Hernou** [comment]
It's in the history that this bug appear...
Yes, I comfirm, this come from pidgin, I don't think that it's a bug... 
You can send an issue on pidgin.im if you want confirm that. :-)
